// قائمة شاملة — إباحية / سكس / porno
// العربية + الدارجة + الدارجة بالفرنسية (Franco-Arabic)

module.exports = [
    // ═══ عربي فصيح ═══
    "إباحي", "إباحية", "إباحيات", "إباح", "اباحي", "اباحية", "اباحيات", "اباح",
    "محتوى إباحي", "محتوى اباحي", "مواد إباحية", "مواد اباحية",
    "فيلم إباحي", "فيلم اباحي", "فيديو إباحي", "فيديو اباحي",
    "أفلام إباحية", "افلام اباحية", "فيديوهات إباحية", "فيديوهات اباحية",
    "صور إباحية", "صور اباحية", "صور عارية", "صور سكس",
    "موقع إباحي", "موقع اباحي", "مواقع إباحية", "مواقع اباحية",
    "قناة إباحية", "قناة اباحية", "قنوات إباحية",
    "سكس", "سكيس", "سكسي", "سكسية", "سكسب",
    "افلام سكس", "أفلام سكس", "فيديو سكس", "فيديوهات سكس",
    "مشاهدة سكس", "تحميل سكس", "سكس مجاني", "رابط سكس", "لينك سكس",
    "جنس", "جنسي", "جنسية", "جنسان", "جنسانية",
    "علاقة جنسية", "ممارسة الجنس", "جماع", "مداعبة",
    "عاري", "عارية", "عري", "عريان", "عريانة", "عرا", "تعري", "عري كامل", "تعري كامل",
    "بورنو", "بورن", "بورنوغرافي", "بورنوغرافية", "بورنограф",
    "شهوة", "شهواني", "شهوانية", "شهوات",
    "فاحش", "فاحشة", "فاحشات", "فحش", "فحشاء",
    "عهر", "عاهرة", "عاهرات", "دعارة", "بغاء", "بغي", "بغايا",
    "زنا", "زاني", "زانية", "زناة", "فاسق", "فسق",
    "عريضة", "للكبار", "للكبار فقط", "محتوى +18", "+18", "18+",
    "استمناء", "onanisme", "masturbation",
    "لذة جنسية", "متعة جنسية", "نشوة",
    "عري مثير", "مثير جنسيا", "إثارة جنسية",
    "مشاهد إباحية", "مشاهد ساخنة", "مشاهد hot",
    "تحميل اباحي", "تحميل إباحي", "تحميل فيلم سكس",
    "رابط اباحي", "رابط إباحي", "لينك اباحي", "لينك إباحي",
    "قروب اباحي", "جروب اباحي", "مجموعة اباحية",
    "بنت عارية", "ولد عريان", "عري بالكامل",
    "فيلم سكس", "serie سكس", "مسلسل إباحي",

    // ═══ دارجة مغربية (عربي) ═══
    "شي حاجة إباحية", "شي حاجة اباحية", "شي حاجة ibhaya",
    "بغيت نشوف سكس", "بغيت سكس", "بغيت فيلم سكس", "بغيت فيديو سكس",
    "عطيني سكس", "عطيني فيلم سكس", "عطيني فيديو سكس", "عطيني شي حاجة إباحية",
    "وريني سكس", "وريني فيلم سكس", "وريني شي حاجة إباحية", "وريني شي ibhaya",
    "فين كاين سكس", "فين لقيت سكس", "كاين سكس", "واش عندك سكس",
    "واش عندك ibhaya", "واش عندك إباحية", "واش كاين porno",
    "بغيت ibhaya", "بغيت إباحية", "بغيت شي ibhaya",
    "شوف سكس", "شوف فيلم سكس", "شوف ibhaya",
    "سكس ديال المغرب", "سكس مغربي", "سكس عربي", "سكس maroc",
    "فيلم ibhaya", "فيديو ibhaya", "site ibhaya",
    "لينك ديال سكس", "رابط ديال سكس", "link ديال porno",
    "telegram سكس", "telegram ibhaya", "تيليغرام سكس",
    "قناة سكس", "قروب سكس", "جروب سكس", "channel سكس",
    "صور ibhaya", "صور سكس", "photos ibhaya",
    "تحميل ibhaya", "telecharger ibhaya", "telecharger porno",
    "شي فيلم ibhaya", "شي video ibhaya", "chi film ibhaya",
    "حاجة hot", "شي حاجة hot", "chi haja hot",
    "حاجة +18", "chi haja +18", "محتوى hot",
    "بنت ibhaya", "بنت سكس", "ولد ibhaya",
    "film kbar", "فيلم كبار", "محتوى كبار",
    "skiz", "skiss", "sikis", "سكيز",

    // ═══ Franco-Arabic (دارجة بالفرançais) ═══
    "ibhaya", "ibahi", "ibahiya", "ibahya", "ibahia", "ibahie",
    "ib7aya", "ib7i", "ib7iya", "ib7ya", "ib7a", "ib7",
    "7ayba", "7aybi", "7aybiya", "7aybia", "7ayb", "7ayba",
    "ibahya", "ibahiya", "ibahie", "ibahiat",
    "skiz", "skiss", "skis", "skizs", "skise",
    "sikis", "sikiss", "siks", "sikise", "sikiz",
    "seks", "seksy", "seksie", "seks video", "seks film",
    "sex", "sexy", "sexe", "sex video", "sex film", "sex site",
    "sex movie", "sex clip", "sex scene", "sex chat",
    "porno", "porn", "pornos", "pornu", "pornou",
    "pornhub", "pornhub.com", "porn hub", "porn-hub",
    "xvideos", "x videos", "xvideo", "x-videos",
    "xhamster", "x hamster", "x-hamster",
    "xnxx", "x nxx", "x-nxx",
    "redtube", "red tube", "red-tube",
    "youporn", "you porn", "you-porn",
    "brazzers", "brazzer", "bangbros", "bang bros",
    "onlyfans", "only fans", "only-fans", "onlyfan",
    "chaturbate", "chatur bate", "livejasmin", "live jasmin",
    "spankbang", "spank bang", "eporner", "e porner",
    "beeg", "tube8", "tube 8", "pornmd", "porn md",
    "thumbzilla", "thumb zilla", "tnaflix", "tna flix",
    "drtuber", "dr tuber", "sunporno", "sun porno",
    "keezmovies", "keez movies", "extremetube",
    "porn300", "porn3000", "porn555", "porn555.com",
    "xxx", "xxxx", "xxxxx", "xxx video", "xxx film",
    "hentai", "hanime", "anime porn", "anime sex",
    "nude", "nudes", "naked", "nude pic", "nude photo",
    "nude video", "nude girl", "nude boy", "nude selfie",
    "nsfw", "nsfw content", "nsfw video", "nsfw pic",
    "adult", "adult video", "adult film", "adult content",
    "adult site", "adult movie", "adult pic", "adult photo",
    "porn video", "porn film", "porn site", "porn movie",
    "porn clip", "porn scene", "porn star", "pornstar",
    "free porn", "watch porn", "download porn", "stream porn",
    "hot video", "hot film", "hot pic", "hot photo", "hot girl",
    "hot scene", "hot clip", "hot content", "hot site",
    "erotic", "erotica", "erotic video", "erotic film",
    "soft porn", "hard porn", "hardcore", "hard core",
    "milf", "teen porn", "amateur porn", "amateur sex",
    "webcam sex", "cam sex", "camgirl", "cam girl", "cam boy",
    "strip", "strip tease", "striptease", "stripchat",
    "boobs", "tits", "ass", "pussy", "dick pic", "dickpic",
    "blowjob", "handjob", "cumshot", "orgasm",
    "fuck", "fucking", "fucked", "fuck video",
    "make love", "making love",

    // ═══ Leetspeak / contournements ═══
    "p0rn", "p0rno", "p0rn0", "pr0n", "pr0no", "pr0n0",
    "p0rnhub", "p0rn hub", "pornhvb", "pornhup",
    "s3x", "s3xy", "s3xe", "s e x", "s.e.x",
    "p o r n", "p o r n o", "p.o.r.n", "p.o.r.n.o",
    "x x x", "x.x.x", "xx x",
    "ib7aya", "1bhaya", "ibh4ya", "ibh@ya",
    "sk1z", "sk!z", "s1k1s", "s!k!s",
    "porn0", "sex0", "sexx", "sexxx",

    // ═══ فرنسي ═══
    "film porno", "video porno", "vidéo porno", "films porno",
    "site porno", "sites porno", "photo porno", "photos porno",
    "film sexe", "video sexe", "vidéo sexe", "films sexe",
    "site sexe", "photos sexe", "contenu sexe",
    "film érotique", "video érotique", "contenu érotique",
    "film pour adulte", "video pour adulte", "contenu adulte",
    "film x", "video x", "film xxx", "video xxx",
    "film coquin", "video coquine", "photo coquine",
    "film hot", "video hot", "photo hot",
    "film cochon", "video cochonne",
    "lien porno", "lien sexe", "lien ibhaya", "lien xxx",
    "link porno", "link sexe", "link ibhaya", "link xxx",
    "lien film porno", "lien video porno",
    "telegram porno", "telegram sexe", "telegram sex",
    "groupe porno", "group porno", "groupe sexe", "group sex",
    "channel porno", "chaine porno", "chaîne porno",
    "canal porno", "canal sexe",
    "telecharger porno", "télécharger porno", "download porno",
    "regarder porno", "watch porno", "voir porno",
    "porno gratuit", "porno free", "free porno", "sexe gratuit",
    "porno maroc", "porno marocain", "porno arabe", "porno arab",
    "porno maghreb", "porno maghrebin", "porno algerie",
    "porno tunisie", "porno marocaine", "porno arabe gratuit",
    "sexe maroc", "sexe marocain", "sexe arabe",
    "film porno maroc", "video porno maroc",
    "porno amateur", "sexe amateur", "amateur porno",
    "chat sexe", "chat porno", "sex chat", "porn chat",
    "webcam porno", "webcam sexe", "cam porno",
    "live porno", "live sexe", "live sex", "live porn",
    "streaming porno", "stream porno", "stream sex",
    "actrice porno", "acteur porno", "porn star",
    "scène porno", "scene porno", "scène sexe",
    "nudité", "nu", "nue", "nus", "nues", "nudiste",
    "seins nus", "fesses nues", "corps nu",
    "masturbation", "branlette", "branler",
    "orgasme", "jouissance", "plaisir sexuel",
    "pénétration", "penetration", "sodomie",
    "fellation", "cunnilingus", "69",
    "partouze", "orgie", "échangisme",
    "salope", "salop", "pute", "putain", "prostituée",
    "baise", "baiser", "baise moi", "baise-moi",
    "niquer", "nique", "enculer", "encule",
    "foutre", "foutre le camp",
    "cul nu", "sexe anal", "anal sex", "anal porn",
    "lesbienne porno", "gay porno", "porno gay", "porno lesbien",
    "trans porno", "shemale", "tranny porn",
    "bdsm", "bondage", "domination", "soumission",
    "fetish", "fétichisme", "fetichisme",
    "voyeur", "voyeurisme", "exhibitionnisme",
    "porno enfant", "mineur porno",

    // ═══ Darija phrases (Franco) ═══
    "chi haja ibhaya", "chi haja ibahi", "chi haja ibahiya",
    "chi haja skiz", "chi haja sikis", "chi haja sex",
    "chi haja hot", "chi haja +18", "chi haja porno",
    "chi film ibhaya", "chi video ibhaya", "chi film skiz",
    "chi video skiz", "chi film sikis", "chi video sikis",
    "chi film porno", "chi video porno", "chi film sex",
    "chi link ibhaya", "chi link porno", "chi link sex",
    "chi lien ibhaya", "chi lien porno", "chi site ibhaya",
    "chi site porno", "chi site sex", "chi site skiz",
    "bghit ibhaya", "bghit ibahi", "bghit ibahiya", "bghit ib7aya",
    "bghit skiz", "bghit skiss", "bghit sikis", "bghit siks",
    "bghit sex", "bghit porno", "bghit porn", "bghit xxx",
    "bghit film ibhaya", "bghit video ibhaya", "bghit film skiz",
    "bghit video skiz", "bghit film porno", "bghit video porno",
    "bghit chi ibhaya", "bghit chi skiz", "bghit chi porno",
    "bghit nchouf ibhaya", "bghit nchouf skiz", "bghit nchouf porno",
    "bghit nchouf sex", "bghit nchouf sikis",
    "bghit telecharger ibhaya", "bghit telecharger porno",
    "bghit download ibhaya", "bghit download porno",
    "wrini ibhaya", "wrini ibahi", "wrini skiz", "wrini sikis",
    "wrini sex", "wrini porno", "wrini xxx", "wrini hot",
    "wrini film ibhaya", "wrini video ibhaya", "wrini film skiz",
    "3tini ibhaya", "3tini skiz", "3tini sikis", "3tini porno",
    "3tini sex", "3tini film ibhaya", "3tini video ibhaya",
    "3tini link ibhaya", "3tini link porno", "3tini lien ibhaya",
    "fin kayn ibhaya", "fin kayn skiz", "fin kayn porno",
    "fin kayn sex", "fin l9it ibhaya", "fin l9it porno",
    "wach 3ndek ibhaya", "wach 3andek ibhaya", "wach endek ibhaya",
    "wach 3ndek skiz", "wach 3ndek porno", "wach 3ndek sex",
    "wach kayn ibhaya", "wach kayn skiz", "wach kayn porno",
    "wach t9der t3tini ibhaya", "wach t9der t3tini porno",
    "wach t9der t3tini skiz", "wach t9der t3tini sex",
    "chouf ibhaya", "chouf skiz", "chouf porno", "chouf sex",
    "chouf li ibhaya", "chouf li porno", "chouf li skiz",
    "send ibhaya", "send porno", "send sex", "send skiz",
    "sift ibhaya", "sift porno", "sift skiz", "sift sex",
    "sift li ibhaya", "sift li porno", "sift li skiz",
    "partage ibhaya", "partage porno", "partage sex",
    "partager ibhaya", "partager porno",
    "groupe ibhaya", "groupe porno", "groupe sex", "groupe skiz",
    "group ibhaya", "group porno", "group sex", "group skiz",
    "channel ibhaya", "channel porno", "channel sex",
    "telegram ibhaya", "telegram porno", "telegram sex",
    "telegram skiz", "telegram sikis",
    "whatsapp ibhaya", "whatsapp porno", "whatsapp sex",
    "fb ibhaya", "facebook ibhaya", "facebook porno",
    "insta ibhaya", "instagram ibhaya", "instagram porno",
    "tiktok ibhaya", "tiktok porno", "tiktok sex",
    "snap ibhaya", "snapchat ibhaya", "snap porno",
    "film ibhaya", "video ibhaya", "film skiz", "video skiz",
    "film sikis", "video sikis", "film sex", "video sex",
    "site ibhaya", "site skiz", "site sikis", "site porno",
    "link ibhaya", "link skiz", "link porno", "link sex",
    "lien ibhaya", "lien skiz", "lien porno", "lien sex",
    "photo ibhaya", "photo skiz", "photo porno", "photo sex",
    "pic ibhaya", "pic porno", "pic sex", "pic hot",
    "image ibhaya", "image porno", "image sex", "image hot",
    "selfie ibhaya", "selfie porno", "selfie hot", "selfie nude",
    "nude ibhaya", "nude pic", "nude photo", "nude video",
    "hot ibhaya", "hot pic", "hot photo", "hot video", "hot film",
    "sexy pic", "sexy photo", "sexy video", "sexy film",
    "porno maroc", "porno maghreb", "porno darija",
    "porno arabe", "porno arab", "porno maghrebin",
    "sexe maroc", "sexe maghreb", "sexe arabe",
    "ibhaya maroc", "ibhaya maghreb", "ibhaya arabe",
    "skiz maroc", "skiz maghreb", "sikis maroc",
    "film ibhaya maroc", "video ibhaya maroc",
    "porno gratuit", "ibhaya gratuit", "skiz gratuit",
    "free ibhaya", "free skiz", "free sex", "free porn",
    "watch ibhaya", "watch skiz", "watch porno",
    "regarder ibhaya", "regarder porno", "regarder skiz",
    "voir ibhaya", "voir porno", "voir skiz",
    "download ibhaya", "download skiz", "download porno",
    "telecharger ibhaya", "telecharger skiz", "telecharger porno",
    "stream ibhaya", "stream porno", "stream sex",
    "live ibhaya", "live porno", "live sex",
    "cam ibhaya", "cam porno", "cam sex", "webcam ibhaya",
    "chat ibhaya", "chat porno", "chat sex",
    "bghit nude", "bghit naked", "bghit hot pic",
    "bghit sexy pic", "bghit photo hot", "bghit video hot",
    "bghit film hot", "bghit chi hot", "bghit chi sexy",
    "bghit chi nude", "bghit chi naked",
    "wrini nude", "wrini naked", "wrini sexy",
    "wrini photo hot", "wrini video hot",
    "3tini nude", "3tini naked", "3tini hot pic",
    "chi nude", "chi naked", "chi sexy", "chi hot",
    "chi photo nude", "chi video nude",
    "bnt ibhaya", "bnt skiz", "bnt porno", "bnt sex",
    "bent ibhaya", "bent skiz", "bent porno",
    "weld ibhaya", "weld skiz", "weld porno",
    "film kbar", "video kbar", "contenu kbar",
    "film adulte", "video adulte", "contenu adulte",
    "film x", "video x", "film xxx", "video xxx",
    "film coquin", "video coquine", "photo coquine",
    "film cochon", "video cochonne",
    "film érotique", "video érotique",
    "film pour adulte", "video pour adulte",

    // ═══ anglais ═══
    "pornography", "pornographic", "pornographic content",
    "sexual content", "sexual video", "sexual film",
    "adult entertainment", "adult material",
    "explicit content", "explicit video", "explicit film",
    "x rated", "x-rated", "rated x", "r rated",
    "blue film", "blue video", "blue movie",
    "smut", "smutty", "smut video",
    "obscene", "obscenity", "obscene content",
    "lewd", "lewd content", "lewd video",
    "vulgar", "vulgar content",
    "indecent", "indecent exposure",
    "erotic movie", "erotic video", "erotic photo",
    "nude scene", "nude video", "nude photo", "nude pic",
    "naked girl", "naked boy", "naked photo", "naked video",
    "strip club", "strip show", "lap dance",
    "escort", "escort service", "call girl",
    "hookup", "hook up", "one night stand",
    "swinger", "swinging", "swingers",
    "threesome", "foursome", "gangbang", "gang bang",
    "deepthroat", "deep throat", "rimjob", "rim job",
    "creampie", "cream pie", "facial cumshot",
    "doggystyle", "doggy style", "missionary",
    "cowgirl", "reverse cowgirl",
    "anal", "anal sex", "anal porn", "anal video",
    "oral sex", "oral porn", "oral video",
    "lesbian", "lesbian porn", "lesbian sex", "lesbian video",
    "gay porn", "gay sex", "gay video", "gay film",
    "bisexual porn", "bi porn",
    "trans porn", "transgender porn", "shemale porn",
    "fetish porn", "fetish video", "kink", "kinky",
    "bdsm porn", "bondage porn", "domination porn",
    "voyeur porn", "voyeur video",
    "revenge porn", "leaked nudes", "leaked video",
    "sex tape", "sextape", "sex scandal",
    "celebrity nude", "celebrity sex tape",
    "deepfake porn", "deep fake porn", "ai porn",
    "rule 34", "rule34", "r34",
    "e621", "furaffinity", "rule34video",
    "missav", "jav", "japanese porn", "japanese av",
    "korean porn", "korean av", "chinese porn",
    "indian porn", "desi porn", "desi sex",
    "arab porn", "arab sex", "arabic porn", "arabic sex",
    "moroccan porn", "morocco porn", "maroc porn",
    "maghreb porn", "maghrebi porn", "african porn",
    "latina porn", "ebony porn", "asian porn",
    "milf porn", "teen porn", "young porn",
    "amateur porn", "homemade porn", "homemade sex",
    "professional porn", "studio porn",
    "vr porn", "vr sex", "virtual porn",
    "interactive porn", "live porn", "live sex cam",
    "sex cam", "porn cam", "adult cam",
    "sex dating", "adult dating", "hookup site",
    "sex shop", "adult shop", "sex toy", "sextoy",
    "dildo", "vibrator", "vibro",
    "lube", "lubricant", "condom porn",
    "playboy", "penthouse", "hustler",
    "pornhub premium", "xvideos red",
    "fansly", "manyvids", "clips4sale",
    "patreon porn", "patreon adult", "patreon nsfw",
    "reddit nsfw", "reddit porn", "nsfw reddit",
    "discord nsfw", "discord porn", "nsfw discord",
    "whatsapp porn", "whatsapp sex", "whatsapp nude",
    "telegram porn", "telegram sex", "telegram nude",
    "telegram channel porn", "telegram group porn",
    "snapchat nude", "snapchat sex", "snap nude",
    "instagram nude", "insta nude", "insta sex",
    "tiktok nude", "tiktok sex", "tiktok porn",
    "twitter porn", "twitter nsfw", "x porn",
    "facebook porn", "fb porn", "fb sex",
    "omegle sex", "omegle porn", "chatroulette porn",
    "dirty talk", "sex talk", "sex chat",
    "phone sex", "sexting", "sext",
    "send nudes", "send nude", "send me nudes",
    "show me nudes", "show nudes", "show nude",
    "want nudes", "need nudes", "got nudes",
    "trade nudes", "exchange nudes", "swap nudes",
    "nude trade", "nude exchange", "nude swap",
    "pic for pic", "pic4pic", "p4p",
    "video call sex", "vc sex", "sex vc",
    "facetime sex", "facetime nude",
    "zoom sex", "zoom nude",
    "watch together porn", "watch porn together"
];
